### ISSUE TITLE
"Export" button produces log only on some browsers

### ISSUE THREAD

**Issue by mmyers1** [elkebir-group/cnaviz#1]
Some browsers (I tried Firefox) will download the log file only, which is insufficient to recover the manual operations made using CNAViz. This may have to do with behavior around multiple downloads from the same trigger.

Easy fix could be to add a drop-down menu or another export button.

**Comment by gillichu** [comment]
Hi Matt - Sorry for the delay in getting back to you; thanks for the bug report. I've created a new button to export the log, which can be found in the Log pop-up. I believe this should work now, but feel free to re-open the issue if you're still having problems.
